URL https://mathdatasimplified.com/

In [ ]:
import pandas as pd

highlight_df = pd.DataFrame(
    {
     "column1": [-5, -2, 1, 4],
     "column2": [2, 3, -1, 4]
    }
)

def highlight_number(row):
    return [
    "background-color: red; color: white"
    if cell < 0
    else "background-color: green; color: white"
    for cell in row
    ]

highlight_df.apply(highlight_number)

,column1,column2
0,background-color: red; color: white,background-color: green; color: white
1,background-color: red; color: white,background-color: green; color: white
2,background-color: green; color: white,background-color: red; color: white
3,background-color: green; color: white,background-color: green; color: white